// Migration script: Move all apps from user1/ paths to /opt/apps/<id>/
// Updates: meta.json, installed.json, registry.json, initd.run

import { readFileSync, writeFileSync, mkdirSync, cpSync, existsSync } from 'fs';
import { join, dirname, basename } from 'path';

const ROOT = '/Users/pankajdevesh/Desktop/Gitea-Workspaces/bootstrapper-js';
const MOUNT = join(ROOT, 'docs/public/mount');

// Read registry
const registry = JSON.parse(readFileSync(join(ROOT, 'docs/registry.json'), 'utf8'));
const meta = JSON.parse(readFileSync(join(MOUNT, 'meta.json'), 'utf8'));

// Track all moves: { oldVfsPath -> newVfsPath }
const moves = new Map();
// Track installed entries
const installedEntries = [];

console.log(`Registry has ${registry.apps.length} apps\n`);

for (const app of registry.apps) {
  const appDir = `/opt/apps/${app.id}`;
  const diskAppDir = join(MOUNT, appDir);

  // Create directory
  mkdirSync(diskAppDir, { recursive: true });

  console.log(`=== ${app.id} (${app.name}) ===`);

  // Copy each file
  for (const file of app.files) {
    // src is like "/public/mount/home/user1/apps/explorer.js"
    const srcDiskPath = join(ROOT, 'docs', file.src);
    const destFileName = file.dest; // e.g. "main.js"
    const destDiskPath = join(diskAppDir, destFileName);

    // Old VFS path (derived from the src)
    const oldVfsPath = file.src.replace('/public/mount', '');
    const newVfsPath = `${appDir}/${destFileName}`;

    if (srcDiskPath === destDiskPath) {
      console.log(`  ${newVfsPath} (already in place)`);
      moves.set(oldVfsPath, newVfsPath);
    } else if (existsSync(srcDiskPath)) {
      mkdirSync(dirname(destDiskPath), { recursive: true });
      cpSync(srcDiskPath, destDiskPath, { force: true });
      console.log(`  ${oldVfsPath} -> ${newVfsPath}`);
      moves.set(oldVfsPath, newVfsPath);
    } else if (existsSync(destDiskPath)) {
      console.log(`  ${newVfsPath} (already exists)`);
    } else {
      console.log(`  WARNING: ${srcDiskPath} not found, skipping`);
    }

    // Update registry src
    file.src = `/public/mount${newVfsPath}`;
  }

  // Update main path
  const mainFile = `${appDir}/${app.main}`;

  // Build installed entry
  installedEntries.push({
    id: app.id,
    name: app.name,
    version: app.version || '1.0.0',
    description: app.description || '',
    icon: app.icon || 'apps',
    category: app.category || 'Other',
    author: app.author || 'bootstrapper-js',
    appDir,
    mainFile,
    commandName: app.commandName || null,
    installedAt: 1750636800000,
  });
}

// Also handle spotlight which is at /opt/spotlight.js (not in registry but needs to move)
const spotlightOld = '/opt/spotlight.js';
const spotlightNew = '/opt/apps/spotlight/main.js';
if (!moves.has(spotlightOld)) {
  const spotlightSrc = join(MOUNT, spotlightOld);
  const spotlightDest = join(MOUNT, spotlightNew);
  if (existsSync(spotlightSrc)) {
    mkdirSync(dirname(spotlightDest), { recursive: true });
    cpSync(spotlightSrc, spotlightDest, { force: true });
    moves.set(spotlightOld, spotlightNew);
    console.log(`\n=== spotlight (system) ===`);
    console.log(`  ${spotlightOld} -> ${spotlightNew}`);
  }
}

// Update meta.json: update paths that were moved, add new entries for new paths
console.log(`\n--- Updating meta.json ---`);
const newMeta = [];
const seenPaths = new Set();

for (const entry of meta) {
  const oldPath = entry.path;
  if (moves.has(oldPath)) {
    const newPath = moves.get(oldPath);
    // Replace with new path
    if (!seenPaths.has(newPath)) {
      newMeta.push({ path: newPath, file: newPath, force_reload: true });
      seenPaths.add(newPath);
      console.log(`  Updated: ${oldPath} -> ${newPath}`);
    }
  } else {
    // Keep as-is
    if (!seenPaths.has(oldPath)) {
      newMeta.push(entry);
      seenPaths.add(oldPath);
    }
  }
}

// Add any new paths from moves that weren't in meta.json
for (const [oldPath, newPath] of moves) {
  if (!seenPaths.has(newPath)) {
    newMeta.push({ path: newPath, file: newPath, force_reload: true });
    seenPaths.add(newPath);
    console.log(`  Added: ${newPath}`);
  }
}

// Write updated files
writeFileSync(join(MOUNT, 'meta.json'), JSON.stringify(newMeta, null, 2) + '\n');
console.log(`  Wrote meta.json (${newMeta.length} entries)`);

writeFileSync(join(MOUNT, 'etc/pkg/installed.json'), JSON.stringify(installedEntries, null, 2) + '\n');
console.log(`  Wrote installed.json (${installedEntries.length} apps)`);

writeFileSync(join(ROOT, 'docs/registry.json'), JSON.stringify(registry, null, 2) + '\n');
console.log(`  Wrote registry.json`);

// Write new initd.run (just load loader.js which loads everything from installed.json)
const initdContent = `/**
 * WARNING:
 * Do not edit this file!
 * This file is automatically updated when the browser is reloaded.
 * If you want to add new programs to run on system initialization, refer to the '/.initd.run' file.
 */

// Load all installed apps (reads /etc/pkg/installed.json, exec's JS apps)
service('root', 'exec')('/opt/pkg/loader.js');

// User custom startup script
service('root', 'exec')('/.initd.run');
`;
writeFileSync(join(MOUNT, 'home/user1/initd.run'), initdContent);
console.log(`  Wrote initd.run`);

console.log('\n--- Summary ---');
console.log(`Moved ${moves.size} file paths`);
console.log(`${installedEntries.length} apps in installed.json`);
console.log(`${newMeta.length} entries in meta.json`);

// Print the JS apps that loader.js will exec at boot
const jsApps = installedEntries.filter(e => e.mainFile.endsWith('.js'));
console.log(`\nJS apps loaded at boot by loader.js (${jsApps.length}):`);
for (const app of jsApps) {
  console.log(`  ${app.id}: ${app.mainFile} -> command: ${app.commandName || '(auto-detect)'}`);
}
