// Load file explorer
service('root', 'exec') ('/home/user1/apps/explorer.js');
service('root', 'exec') ('/home/user1/info.html');
// service('root', 'exec') ('/home/user1/apps/xtermjs.html');

// service('001-core.layout', 'open-window') (command('ui.iframe'), '/home/user1/index.html');
// service('003-core.iframe', 'fullscreen') ();

// service('001-core.layout', 'open-window') (command('ui.iframe'), '/home/user1/projects/three.html');
